const fs = require('fs');

const additions = `// --- NEW FIELDS FOR Contract ---
  abonar String?
  actualizarconsumo String?
  ajustePen String?
  aLTAfromCONTRATOPREVIO String?
  aoFirma Int?
  aPELLIDOS String?
  apellidosContacto String?
  aTRCOMER String?
  autoconsumo String?
  bAJAPORM1RE1 String?
  bajasGlide String?
  bIMENSUAL String?
  bIPen String?
  bOLSILLOSOLAR String?
  borradorcontrato String?
  bUSCADOR String?
  cAfromPROVLINK String?
  cALCULOMESALTA String?
  cALCULOMESBAJA String?
  cANAL String?
  cAPTACIONCLIENTE String?
  cG String?
  cIE String?
  cIERRE String?
  cODREEDISTRILINK String?
  cdigoCanal String?
  cdigocomercial String?
  cdigoCUPS String?
  cdigoPostalInstalacin String?
  cODIGOREEDISTRIBUIDORA String?
  cdigoTarifa String?
  comentarioAED String?
  cOMISION Float?
  cOMISIONfromCOMISIONES Float?
  cOMISION50 Float?
  cOMISIONFINAL Float?
  comisinRevisable String?
  cOMISIONSIBAJAHOY Float?
  cOMISIONVARIABLE Float?
  cOMISIONACTIVA Float?
  cOMISIONESTIMADA Float?
  cOMISIONES Float?
  cONSUMOCOMISION Float?
  cONSUMOREALESTIMADO Float?
  contratoenviado String?
  contratofirmado String?
  cONTRATOPREVIO String?
  cONTRATO2 String?
  cONTROLSAGE String?
  cPCONT String?
  dECOMISION String?
  dECOMISION50 String?
  demandaAbril Float?
  demandaBCAgosto Float?
  demandaBCDiciembre Float?
  demandaBCEnero Float?
  demandaBCJulio Float?
  demandaBCJunio Float?
  demandaBCMarzo Float?
  demandaBCNoviembre Float?
  demandaBCOctubre Float?
  demandaBCSeptiembre Float?
  demandaFebrero Float?
  demandaMANUALAbril Float?
  demandaMANUALAgosto Float?
  demandaMANUALDiciembre Float?
  demandaMANUALEnero Float?
  demandaMANUALFebrero Float?
  demandaMANUALJulio Float?
  demandaMANUALJunio Float?
  demandaMANUALMarzo Float?
  demandaMANUALMayo Float?
  demandaMANUALNoviembre Float?
  demandaMANUALOctubre Float?
  demandaMANUALSeptiembre Float?
  demandaMayo Float?
  dEMANDAREALPREVISTA String?
  derechosExtension String?
  dESCUENTOCIE String?
  daActual Int?
  dIASCONTRATO String?
  dIASFACTURADOS String?
  dIASPAGO String?
  dIASVIDACLIENTE String?
  dIASRENOVMAX String?
  dISTRIBUIDORA String?
  dNINIFTitular String?
  dOMICILIOPS String?
  dOMICILIOPSCOMPLETO String?
  domicilioTitularCompleto String?
  dOMICILIOCONT String?
  dSVIndexfromPRODUCTOS String?
  dURACION String?
  dURACIONSVA String?
  eFACTURA String?
  eMAILCOMER String?
  eMAILFACTURA String?
  eMAIL4 String?
  eMPRESA String?
  eNCALIDADDE String?
  eNERGIAFACTURADA String?
  energaPteMes1 String?
  energaPteMes2 String?
  energaPteMes0HastaFINMES String?
  energaPteMes0HastaHOY String?
  enlaceWp String?
  envodefactura String?
  eQUIPODISTRIB String?
  eSTADOfromCONTRATOPREVIO String?
  excedentesAbril Float?
  excedentesAgosto Float?
  excedentesDic Float?
  excedentesEne Float?
  excedentesFeb Float?
  excedentesJulio Float?
  excedentesJunio Float?
  excedentesMANUALAbril Float?
  excedentesMANUALAgosto Float?
  excedentesMANUALDiciembre Float?
  excedentesMANUALEnero Float?
  excedentesMANUALFebrero Float?
  excedentesMANUALJulio Float?
  excedentesMANUALJunio Float?
  excedentesMANUALMarzo Float?
  excedentesMANUALMayo Float?
  excedentesMANUALNoviembre Float?
  excedentesMANUALOctubre Float?
  excedentesMANUALSeptiembre Float?
  excedentesMarzo Float?
  excedentesMayo Float?
  excedentesNoviembre Float?
  excedentesOctubre Float?
  excedentesSept Float?
  facturaenpapel String?
  fACTURASINO String?
  facturarPen String?
  fACTURAS String?
  fACTURAS2 String?
  fC String?
  fechaAceptacin DateTime?
  fechaActual DateTime?
  fechaBorrador DateTime?
  fechafirma DateTime?
  fechafirmacontrato DateTime?
  fechaIncidencia DateTime?
  fECHAINICIOSVA String?
  fechaPrevistaActivacin DateTime?
  fechaProceso DateTime?
  fechaRechazo DateTime?
  fechaRegistro DateTime?
  fechaRenovacinCalculada DateTime?
  fechaSolicitud DateTime?
  fechaVencimientoCalculada DateTime?
  fECHABAJAESTIMADA String?
  fechaprevista DateTime?
  fECHARENOVPREVISTA String?
  fechaFacturaPenalizacion DateTime?
  feeExcedentesfromPRODUCTOS Float?
  feeIndexfromPRODUCTOS String?
  fEEIndexPersonalizado String?
  fEEP String?
  field198 String?
  fIJOINDEX String?
  finMes1 String?
  finMes2 String?
  finMes0 String?
  firmamanuscrita String?
  firmaManRenov String?
  formadepago String?
  gASINCLUIDO String?
  generarAnexoM1 String?
  generarBorrador String?
  horaActual String?
  hORASUSODIARIOS String?
  iD String?
  iDGoogleDrivePDF String?
  inicioMes1 String?
  inicioMes2 String?
  inicioMes0 String?
  iNICIOPROCESO String?
  iP String?
  iPP1 Float?
  iPP2 Float?
  iPP3 Float?
  iPP4 Float?
  iPP5 Float?
  iPP6 Float?
  iVAPen String?
  lEADS String?
  lINKTIPOSTARIFA String?
  m1Activado String?
  m1Rechazado String?
  m1NSOLICITADO String?
  m1SSOLICITADO String?
  mailActivacionEnviado String?
  mailBienvenidaEnviado String?
  mANDATODOBLE String?
  mARCA String?
  mensajeDistribuidora String?
  mesActual String?
  mESALTA String?
  mESBAJA String?
  mesespermanencia String?
  minActual String?
  modalidadAutoconsumofromProducto String?
  modalidaddecontrato String?
  mODIFICACIONES String?
  nSolicitud String?
  nCIE String?
  nombreDistribuidora String?
  nombreInstalacin String?
  nombreWp String?
  numFacturaPenalizacion String?
  oCULTARRENOVACION String?
  oDOO String?
  oWNERS String?
  p1CW Float?
  p1EfromPRODUCTOS Float?
  p1PfromPRODUCTOS Float?
  p1PM Float?
  p2CW Float?
  p2EfromPRODUCTOS Float?
  p2P Float?
  p2PfromPRODUCTOS Float?
  p3CW Float?
  p3EfromPRODUCTOS Float?
  p3P Float?
  p3PfromPRODUCTOS Float?
  p4CW Float?
  p4EfromPRODUCTOS Float?
  p4P Float?
  p4PfromPRODUCTOS Float?
  p5CW Float?
  p5EfromPRODUCTOS Float?
  p5P Float?
  p5PfromPRODUCTOS Float?
  p6EfromPRODUCTOS Float?
  p6P Float?
  p6PfromPRODUCTOS Float?
  pasTitular String?
  pEN20TDRESID String?
  pEN20TDRESIDHOY String?
  pENNORESID String?
  pENALIZACION Float?
  pENALIZACIONESTIMADA Float?
  penalizacionFacturada String?
  pENALIZACIONHOY Float?
  peticionclientec2 String?
  pExc String?
  pExcfromPRODUCTOS Float?
  pLUS String?
  pOBLACIONCONT String?
  pOTENCIABOE String?
  pOTENCIASDISTRI String?
  preciofromSERVICIOS Float?
  producto String?
  productoyServicio String?
  pRODUCTORENOVACION String?
  productoLINK String?
  pROVLINK String?
  pROVINCIACONT String?
  pROYECCIONANUAL String?
  recordID String?
  refcat String?
  rENOVACION String?
  rENOVACIONSOLICITADA String?
  rENOVACIONTRAMITADA String?
  renovar String?
  rETRASO String?
  servicio String?
  sERVICIORENOVACION String?
  sINCOMISION Float?
  sINDECOMISION String?
  sINPENALIZACION Float?
  softrTlfn String?
  sUSPENDIDO String?
  sVAAADIDOTERA String?
  sWIFT String?
  telfonoContacto String?
  telegestion String?
  tipo String?
  tipodefirma String?
  tipodenumeracinInstalacin String?
  tipodenumeracinTitular String?
  tipodepersona String?
  tipodeproducto String?
  tipodeproductofromProducto String?
  tipoIdentificador String?
  tipoSolAdmin String?
  tIpoc2 String?
  tipodecliente String?
  tipoentrada String?
  tIPOENVIOFACTURARENOV String?
  tipoSop String?
  tipoPM String?
  tLFCOMER String?
  tramitacinLINK String?
  tramitar String?
  transferencia String?
  uLTDIAAFACTURAR String?
  uLTDIAFACT String?
  uLTIMODIAFACTURADO String?
  uNPRECIO String?
  version String?

// --- NEW FIELDS FOR Lead ---
  autoconsumo String?
  comisinFijo Float?
  comisinVariable Float?
  actualizarSIPSINGEBAU String?
  actualizarSIPSIngebauScript String?
  actualizarSIPSPropioScript String?
  aJUSTECOMISIONDURACIONPOTENCIA Float?
  aJUSTECONSUMOCOMISION Float?
  aLTACOMERCIALIZADORA String?
  aoFirma Int?
  apellidosContacto String?
  aTRCOMER String?
  bAJACOMERCIALIZADORA String?
  bOLSILLOSOLAR String?
  bOLSILLOSOLARfromProductos String?
  borradorcontrato String?
  calculoCodDistri String?
  canal String?
  cAPTACIONCLIENTE String?
  cG String?
  cGBOLSILLOSOLARfromProductos String?
  cIEConsumo String?
  cIERRE String?
  codAutoconsumoSIPS String?
  cdigoCanal String?
  cdigocomercial String?
  cdigoPostalInstalacin String?
  cdigopostalTitular String?
  cODIGOREEDISTRIBUIDORA String?
  comercial String?
  cOMISION Float?
  cOMISIONAJUSTADA Float?
  cOMISIONESTIMADA Float?
  cOMISIONVARIABLE Float?
  cONSUMOANUAL Float?
  contratofirmado String?
  cONTRATOSOP String?
  cONTRATO2 String?
  cONTRATOS String?
  cPSIPS String?
  cPCONT String?
  cUPS2 String?
  dECOMISIONSOBREAJUSTE String?
  dESCUENTOCIE String?
  daBorrador Int?
  dIASPAGO String?
  digitosCUPS String?
  dISTRIBUIDORA String?
  dNINIFTitular String?
  dOMICILIOPS String?
  dOMICILIOPSCOMPLETO String?
  dOMICILIOCONT String?
  dSVIndexfromPRODUCTOS String?
  dURACION String?
  dURACIONSVA String?
  eFACTURA String?
  eMAILCOMER String?
  eMAILFACTURA String?
  eMAIL4 String?
  eMPRESA String?
  eNCALIDADDE String?
  enlaceWp String?
  envodefactura String?
  eQUIPODISTRIB String?
  errorAutoconsumo String?
  errorCNAE String?
  errorCP String?
  errorNIFapoderado String?
  errorPostal String?
  errorTarifa String?
  errorTarifaProducto String?
  escrituras String?
  estadoCompilacindeCONTRATOS String?
  facturaenpapel String?
  fACTURASINO String?
  fC String?
  fechaBorrador DateTime?
  fechaBorradorModificado DateTime?
  fechafirma DateTime?
  fechafirmacontrato DateTime?
  fECHAINICIOSVA String?
  fECHAPREVISTA String?
  fechaRegistro DateTime?
  fECHABAJAESTIMADA String?
  fECHAULTMODSIPS String?
  feeExcedentesfromPRODUCTOS Float?
  feeIndexfromPRODUCTOS String?
  fEEIndexPersonalizado String?
  fEEP String?
  fIJOINDEX String?
  firmamanuscrita String?
  formadepago String?
  gASINCLUIDO String?
  gENCONTRATOAUTO String?
  generarBorrador String?
  horaBorrador String?
  iD String?
  iNICIOPROCESO String?
  iP String?
  iPP1 Float?
  iPP2 Float?
  iPP3 Float?
  iPP4 Float?
  iPP5 Float?
  iPP6 Float?
  mANDATODOBLE String?
  mARCA String?
  mesBorrador String?
  mesespermanenciafromPRODUCTOS String?
  minBorrador String?
  modalidadAutoconsumofromProducto String?
  modalidaddecontrato String?
  nCIE String?
  nombreInstalacin String?
  nombreWp String?
  oDOO String?
  p1CSIPS Float?
  p1EfromPRODUCTOS Float?
  p1PfromPRODUCTOS Float?
  p1PM Float?
  p2CSIPS Float?
  p2EfromPRODUCTOS Float?
  p2P Float?
  p2PfromPRODUCTOS Float?
  p3CSIPS Float?
  p3EfromPRODUCTOS Float?
  p3P Float?
  p3PfromPRODUCTOS Float?
  p4CSIPS Float?
  p4EfromPRODUCTOS Float?
  p4P Float?
  p4PfromPRODUCTOS Float?
  p5CSIPS Float?
  p5EfromPRODUCTOS Float?
  p5P Float?
  p5PfromPRODUCTOS Float?
  p6CSIPS Float?
  p6EfromPRODUCTOS Float?
  p6P Float?
  p6PfromPRODUCTOS Float?
  pasTitular String?
  pCSIPSsuma Float?
  pCsuma Float?
  peticionclientec2 String?
  pExc String?
  pExcfromPRODUCTOS Float?
  pExcPersonalizado String?
  pLUS String?
  pOBLACIONCONT String?
  pOTENCIABOE String?
  pOTENCIASDISTRI String?
  preciofromSERVICIOS Float?
  primerapellidoTitular String?
  producto String?
  productoSop String?
  pROVINCIACONT String?
  recordIDfromCONTRATOS String?
  rehacerBorrador String?
  segundoapellidoTitular String?
  servicio String?
  sIPSOK Boolean?
  sUSPENDIDO String?
  sWIFT String?
  tarifaProducto String?
  tarifaSIPS String?
  telfonoContacto String?
  tIPO String?
  tIPOC2 String?
  tipodefirma String?
  tipodenumeracinInstalacin String?
  tipodenumeracinTitular String?
  tipodepersona String?
  tipodeproducto String?
  tipodeproductofromProducto String?
  tIPOENTRADA String?
  tLFCOMER String?
  tramitacinarealizar String?
  tramitacinSop String?
  triggerDuplicar String?
  ultFactura String?
  uNPRECIO String?
  varPC String?
  vERIFICACIONSOLICITADA String?

// --- NEW FIELDS FOR Invoice ---
  subtotal1 String?
  subtotal2 String?
  subtotalOtrosConcepto String?
  importeBonoSocial Float?
  importeAplicableCompensacionExcedentes Float?
  importePotenciaFactura Float?
  importeEnergiaFactura Float?
  importeEnergiasinMargen Float?
  baseImponibleF1 Float?
  baseImponible0 Float?
  baseImponible10 Float?
  baseImponible21 Float?
  baseImponible5 Float?
  alquilerEquipodeMedida String?
  codigoFacturaRectificadaAnulada String?
  excedentesP1Autoconsumo Float?
  excedentesP2Autoconsumo Float?
  importeR1P1 Float?
  importeR1P2 Float?
  p1PotenciaContratada Float?
  p1PotenciaMaxDemanda Float?
  p2PotenciaContratada Float?
  p2PotenciaMaxDemanda Float?
  potenciaaFacturarP1 Float?
  potenciaaFacturarP2 Float?
  descuentoBolsilloSolar String?
  domicilioTitular String?
  p1EnergiaActivaConsumida Float?
  p2EnergiaActivaConsumida Float?
  p3EnergiaActivaConsumida Float?
  p4EnergiaActivaConsumida Float?
  p5EnergiaActivaConsumida Float?
  p6EnergiaActivaConsumida Float?
  p1EnergiaReactivaConsumida Float?
  p2EnergiaReactivaConsumida Float?
  p3EnergiaReactivaConsumida Float?
  p4EnergiaReactivaConsumida Float?
  p5EnergiaReactivaConsumida Float?
  p6EnergiaReactivaConsumida Float?
  importeExcedentesAutoconsumo Float?
  excedentesAutoconsumoafacturar Float?
  nombreCompletoTitular String?
  avisoTransfPagoFtra String?
  base560 Float?
  baseImponibleAyuntamiento Float?
  baseImponibleTasaMunicipal Float?
  cargaBolsilloSolar String?
  claseFactura String?
  codigoFiscal String?
  comisionCostesdeGestion Float?
  comisionGapAutoconsumo Float?
  comisionImporteExcedentario Float?
  comisionPotenciaCanal String?
  comisionPrecioEnergia Float?
  comisionPrecioFijoEnergia Float?
  comisionSemiindexadoAnual Float?
  comisionTotal Float?
  comisionVolumenEnergia Float?
  comunicar String?
  conceptoRepercutible String?
  conceptoRepercutible1 String?
  conceptoRepercutible2 String?
  conceptoRepercutible3 String?
  correopostalenviado String?
  costesdeGestionBolsilloSolar String?
  disponibilidadLectura String?
  duracion String?
  envodefacturafromContrato String?
  excTotal String?
  excedentesP3Autoconsumo Float?
  excedentesP4Autoconsumo Float?
  excedentesP5Autoconsumo Float?
  excedentesP6Autoconsumo Float?
  facturado String?
  formaenvodelafacturafromCdigoContrato String?
  importeAhorroCargos Float?
  importeAjusteGas Float?
  importealmacenadoBolsilloSolar Float?
  importeCargoEnergiaTotal Float?
  importeCargoPotenciaTotal Float?
  importeConceptoRepercutible1 Float?
  importeConceptoRepercutible2 Float?
  importeConceptoRepercutible3 Float?
  importeExcedentesAutoconsumoAplicado Float?
  importePenalizaciones Float?
  importeR1P3 Float?
  importeR1P4 Float?
  importeR1P5 Float?
  importeR1P6 Float?
  importeTotalCoberturas Float?
  inicioBolsilloSolar String?
  mailenviado String?
  margenEnergia String?
  margenEstimado String?
  margenExcesos String?
  margenFactura String?
  margenPotencia String?
  margenRelIngebau String?
  minimoImporteIESuperado Float?
  mostrarWeb String?
  nombreProductofromContrato String?
  numeroDiasAlquiler1 String?
  numeroDiasAlquiler2 String?
  numeroDiasAlquiler3 String?
  numeroDiasAlquiler4 String?
  p3PotenciaContratada Float?
  p3PotenciaMaxDemanda Float?
  p4PotenciaContratada Float?
  p4PotenciaMaxDemanda Float?
  p5PotenciaContratada Float?
  p5PotenciaMaxDemanda Float?
  p6PotenciaContratada Float?
  p6PotenciaMaxDemanda Float?
  porcentajePerdidas String?
  potenciaaFacturarP3 Float?
  potenciaaFacturarP4 Float?
  potenciaaFacturarP5 Float?
  potenciaaFacturarP6 Float?
  precioConceptoRepercutible1 String?
  precioConceptoRepercutible2 String?
  precioConceptoRepercutible3 String?
  precioDiaAlquiler1 String?
  precioDiaAlquiler2 String?
  precioDiaAlquiler3 String?
  precioDiaAlquiler4 String?
  precioMix String?
  propiedadExcedentes Float?
  recargoInfAnio String?
  recordatorioVtoFtra String?
  suplementoTerritorial String?
  tasaMunicipal String?
  tasaMunicipalForm String?
  telefonoContacto String?
  tipoAutoconsumoDistribuidora String?
  totalsinDescuento String?
  totalSoftr String?
  totalImporteCargos Float?
  totalImportePeajes Float?
  unidadesMix String?
  p1PrecioEnergiaReactiva Float?
  p2PrecioEnergiaReactiva Float?
  p3PrecioEnergiaReactiva Float?
  p4PrecioEnergiaReactiva Float?
  p5PrecioEnergiaReactiva Float?
  p6PrecioEnergiaReactiva Float?
  pExcedentes Float?

// --- NEW FIELDS FOR SupplyPoint ---
  bajaMasReciente String?
  conteoContratosconAlta String?
  conteoContratosconBaja String?
  dIASACTIVO String?
  dIASFACTURADOS String?
  fACTURADODESDE String?
  hUECOFACTURACION String?
  hUECOREVISADO String?
  uLTDIAFACTURADO String?

// --- NEW FIELDS FOR Product ---
  gASINCLUIDO String?
  p1ECosteEstimado Float?
  p1Pd Float?
  p2ECosteEstimado Float?
  p2Pd Float?
  p3ECosteEstimado Float?
  p3Pd Float?
  p4ECosteEstimado Float?
  p4Pd Float?
  p5ECosteEstimado Float?
  p5Pd Float?
  p6ECosteEstimado Float?
  p6Pd Float?`;

let schema = fs.readFileSync('prisma/schema.prisma', 'utf8');

const models = additions.split('// --- NEW FIELDS FOR ').slice(1);
for (const mod of models) {
    const lines = mod.split('\n');
    const modelName = lines[0].split(' ---')[0].trim();
    
    // Find the model block
    const modelStartIdx = schema.indexOf(`model ${modelName} {`);
    if (modelStartIdx === -1) continue;
    const modelEndIdx = schema.indexOf('}', modelStartIdx);
    const modelBlock = schema.substring(modelStartIdx, modelEndIdx);
    
    const fieldsToInject = [];
    for (let i = 1; i < lines.length; i++) {
        const line = lines[i];
        if (!line.trim()) continue;
        const fieldName = line.trim().split(' ')[0];
        // Check if fieldName exists in this model block
        const regex = new RegExp(`\\b${fieldName}\\b`, 'i');
        if (!regex.test(modelBlock)) {
            fieldsToInject.push(line);
        } else {
            console.log(`Skipping ${fieldName} in ${modelName}, already exists.`);
        }
    }
    
    if (fieldsToInject.length > 0) {
        const fields = fieldsToInject.join('\n');
        const replaceRegex = new RegExp(`model ${modelName} \\{[\\s\\S]*?(\n})`);
        schema = schema.replace(replaceRegex, (match, p1) => {
            return match.replace(p1, `\n  // ---> NEW AIRTABLE FIELDS\n${fields}${p1}`);
        });
    }
}

fs.writeFileSync('prisma/schema.prisma', schema);
console.log('Injected new fields into schema.prisma');
