const fs = require('fs');
const text = `
137. **Regla 137 (Fusión Inteligente de Ficheros H y QH en REE/Reganecu)**: Los ficheros de liquidación de REE publican componentes cuarto-horarios (QH) como BS3, CBM, DSV y componentes horarios (H) como CAD y PC3. El ingestor del CRM almacena ambos en la base de datos de manera independiente. Queda terminantemente prohibido 'deduplicar' por fecha descartando el fichero H en favor del QH a nivel de consulta global. La extracción de datos (mes o día) DEBE realizar una fusión a nivel de concepto: se priorizan los conceptos del QH, pero se rescatan y suman los conceptos exclusivos del H que no existen en el QH, garantizando que el coste de la energía (BS3) y el coste de la demanda (CAD/PC3) convivan sin duplicar MWh.

138. **Regla 138 (Robustez en Importación de Conceptos REE)**: REE ocasionalmente publica los conceptos en formato descriptivo íntegro (ej. 'Costes asignados a la demanda', 'Pagos capacidad (Financiación)') en lugar de sus acrónimos cortos. El importador de Reganecu NO debe establecer límites de longitud restrictivos (ej. 20 caracteres) para el nombre del concepto que asuman que siempre es un acrónimo de 3 letras, ampliando el margen de seguridad a 80 caracteres para evitar silenciamientos de importes millonarios por truncamiento.

139. **Regla 139 (Estructura Multi-Nivel y Totales Calculados en Visores)**: Dado que OMIE y REE no inyectan filas explícitas de 'Total' en sus ficheros CSV (solo en sus PDFs), los visores del ERP (Reganecu, Compodem) y sus respectivas exportaciones a Excel DEBEN auto-calcular y añadir dinámicamente la fila 'Total' en el backend durante la respuesta de la API, sumando algebraicamente el resultado de todos los conceptos para evitar descuadres de cara al departamento financiero. Asimismo, la ordenación de los conceptos en UI debe seguir estrictamente la nomenclatura y orden oficial de presentación de la entidad (ej: BS3, CBM, RAD3, CAD, DSV, PC3).
`;
fs.appendFileSync('docs/BUSINESS_RULES.md', text, 'utf8');
