// Fichero autogenerado con los códigos de las tablas maestras de la CNMC
export interface CnmcCode { codigo: string; descripcion: string; }

export const CNMC_DROPDOWN_OPTIONS: Record<string, CnmcCode[]> = {
  "TIPO ATENCION INCORRECTA": [
    { codigo: "01", descripcion: "01 - No existe Punto de Suministro asociado al CUPS" },
    { codigo: "02", descripcion: "02 - Inexistencia de Contrato de ATR previo en vigor" },
    { codigo: "03", descripcion: "03 - NIF-CIF No coincide con el del Contrato en vigor" },
    { codigo: "03", descripcion: "03 - NIF-CIF No coincide con el del Contrato en vigor" },
    { codigo: "06", descripcion: "06 - Existencia de Solicitud ATR previa en curso" },
    { codigo: "07", descripcion: "07 - Tipo de Contrato sin informar o erróneo" },
    { codigo: "08", descripcion: "08 - Fecha de finalización del Contrato sin informar o no válida" },
    { codigo: "09", descripcion: "09 - Existencia de sentencia judicial relativa a deuda del cliente" },
    { codigo: "11", descripcion: "11 - Comercializadora incorrecta" },
    { codigo: "12", descripcion: "12 - Contrato cortado por impago" },
    { codigo: "12", descripcion: "12 - Contrato cortado por impago" },
    { codigo: "13", descripcion: "13 - Potencias No Normalizadas en Tarifas 2.XA y 2.XDHA" },
    { codigo: "14", descripcion: "14 - Potencia Solicitada mayor que la Potencia Máxima Autorizada en baja tensión" },
    { codigo: "15", descripcion: "15 - Secuencia de Potencias incorrectas, Pi>Pi+1" },
    { codigo: "17", descripcion: "17 - Tarifa no válida para la Tensión de Suministro" },
    { codigo: "18", descripcion: "18 - Equipo nuevo propiedad del Cliente no cumple los criterios de Contratación ATR" },
    { codigo: "20", descripcion: "20 - Instalación no disponible o ampliación suministro en trámite (Expediente Abierto + Código de Expediente + Motivo de Expediente)" },
    { codigo: "21", descripcion: "21 - Existencia de Contrato Previo en vigor" },
    { codigo: "22", descripcion: "22 - Potencia Solicitada mayor que la Potencia Máxima Reconocida de Extensión" },
    { codigo: "23", descripcion: "23 - CNAE No Informado o no válido" },
    { codigo: "25", descripcion: "25 - Ausencia del Titular con Cita" },
    { codigo: "26", descripcion: "26 - Acceso imposibilitado más de dos veces por causas ajenas a la Distribuidora" },
    { codigo: "27", descripcion: "27 - Caja ICP no válida o inexistente" },
    { codigo: "28", descripcion: "28 - Rechazo por Anormalidad" },
    { codigo: "29", descripcion: "29 - Falta Equipo Cliente" },
    { codigo: "31", descripcion: "31 - Impedimento del Titular" },
    { codigo: "32", descripcion: "32 - Suministro Esencial" },
    { codigo: "34", descripcion: "34 - Cliente no cortable por orden judicial o administrativa" },
    { codigo: "35", descripcion: "35 - Cliente ya cortado" },
    { codigo: "36", descripcion: "36 - NIF-CIF Erróneo" },
    { codigo: "37", descripcion: "37 - Existencia de Solicitud previa en curso A3" },
    { codigo: "38", descripcion: "38 - Existencia de Solicitud previa en curso C1" },
    { codigo: "39", descripcion: "39 - Existencia de Solicitud previa en curso C2" },
    { codigo: "40", descripcion: "40 - Existencia de Solicitud previa en curso M1" },
    { codigo: "41", descripcion: "41 - Existencia de Solicitud previa en curso B1 (motivo" },
    { codigo: "42", descripcion: "42 - No es posible anulación. OT ya en campo o acciones no anulables en una reclamación" },
    { codigo: "42", descripcion: "42 - No es posible anulación. OT ya en campo o acciones no anulables en una reclamación" },
    { codigo: "43", descripcion: "43 - No es posible anulación. Solicitud ya activada" },
    { codigo: "44", descripcion: "44 - Error en las horas de utilización (Eventuales)" },
    { codigo: "45", descripcion: "45 - Fecha de Finalización de Contrato sin informar (Eventuales, Temporada y Obras)" },
    { codigo: "46", descripcion: "46 - Fecha de la operación solicitada con carácter retroactivo" },
    { codigo: "47", descripcion: "47 - Potencias No Normalizadas en Suministro Trifásico" },
    { codigo: "48", descripcion: "48 - Potencias No Normalizadas en Suministro Monofásico" },
    { codigo: "49", descripcion: "49 - Necesario cambio de Tensión Monofásica a Trifásica" },
    { codigo: "50", descripcion: "50 - Transformadores de medida fuera de rango" },
    { codigo: "51", descripcion: "51 - Tarifa no válida para Contratos de Peaje" },
    { codigo: "52", descripcion: "52 - Tarifa no válida para Potencias Solicitadas" },
    { codigo: "53", descripcion: "53 - Necesidad de abrir Expediente de Acometida" },
    { codigo: "54", descripcion: "54 - No Existe Boletín Eventual" },
    { codigo: "55", descripcion: "55 - Nuevo Cliente coincide con el Actual" },
    { codigo: "56", descripcion: "56 - Falta de Datos en Campo 84 en Modificaciones" },
    { codigo: "57", descripcion: "57 - Falta documentación técnica de baja tensión" },
    { codigo: "58", descripcion: "58 - Falta teléfono de contacto" },
    { codigo: "58", descripcion: "58 - Falta teléfono de contacto" },
    { codigo: "59", descripcion: "59 - Armario / Módulo no válido o inexistente" },
    { codigo: "60", descripcion: "60 - Instalación incompleta o con elementos no válidos" },
    { codigo: "61", descripcion: "61 - CGP no válida o inexistente" },
    { codigo: "62", descripcion: "62 - Actuación Solicitada por Comercializador no acorde con requerimientos Cliente" },
    { codigo: "63", descripcion: "63 - Potencia Solicitada no puede ser inferior a Potencia de B.I.E. (Suministros en Modo 2 no interrumpibles)" },
    { codigo: "64", descripcion: "64 - Desconexión no posible técnicamente en Corte" },
    { codigo: "64", descripcion: "64 - Desconexión no posible técnicamente en Corte" },
    { codigo: "65", descripcion: "65 - Más de una modificación de potencia en un punto de suministro en menos de 12 meses para el mismo titular del punto de suministro" },
    { codigo: "66", descripcion: "66 - Suministro telegestionado." },
    { codigo: "67", descripcion: "67 - Suministro con maxímetro." },
    { codigo: "68", descripcion: "68 - No permitido a comercializadora de ML" },
    { codigo: "69", descripcion: "69 - El distribuidor no está de acuerdo" },
    { codigo: "70", descripcion: "70 - Comercializador inhabilitado" },
    { codigo: "71", descripcion: "71 - Existen varios cont. para el mismo suministro" },
    { codigo: "72", descripcion: "72 - Contrato en baja" },
    { codigo: "73", descripcion: "73 - Sum. Con potencia     > 15 kW." },
    { codigo: "73", descripcion: "73 - Sum. Con potencia     > 15 kW." },
    { codigo: "74", descripcion: "74 - Suministro con más de un contador" },
    { codigo: "75", descripcion: "75 - Discrepancia entre información de lecturas y número de integradores" },
    { codigo: "76", descripcion: "76 - Más dígitos que número de ruedas" },
    { codigo: "77", descripcion: "77 - Lectura menor a ultima real" },
    { codigo: "78", descripcion: "78 - Consumo excesivo" },
    { codigo: "79", descripcion: "79 - Periodo de lectura inferior" },
    { codigo: "80", descripcion: "80 - Suministro con maxímetro y/o reactiva" },
    { codigo: "83", descripcion: "83 - Pobreza Energética" },
    { codigo: "84", descripcion: "84 - Reclamación Duplicada" },
    { codigo: "85", descripcion: "85 - Falta campo obligatorio \"xxxx\"" },
    { codigo: "86", descripcion: "86 - Código de Expediente de Acometida Erróneo" },
    { codigo: "87", descripcion: "87 - Factura inexistente" },
    { codigo: "88", descripcion: "88 - Factura no telegestionada" },
    { codigo: "89", descripcion: "89 - No existe mejor curva disponible (no se genera curva)" },
    { codigo: "90", descripcion: "90 - Autoconsumo 1 o 2B: Titular del consumo no coincide con el de la instalación" },
    { codigo: "91", descripcion: "91 - Autoconsumo: Falta solicitud del contrato asociado" },
    { codigo: "91", descripcion: "91 - Autoconsumo: Falta solicitud del contrato asociado" },
    { codigo: "91", descripcion: "91 - Autoconsumo: Falta solicitud del contrato asociado" },
    { codigo: "92", descripcion: "92 - Autoconsumo: No coincide la categoría del autoconsumo de la solicitud con el registrado en Distribuidora." },
    { codigo: "93", descripcion: "93 - Autoconsumo:  Tipo de autoconsumo no válido." },
    { codigo: "94", descripcion: "94 - Autoconsumo: Imposible tramitar solicitud sobre ese suministro" },
    { codigo: "95", descripcion: "95 - Autoconsumo: Modalidad solicitada no coincide contrato técnico." },
    { codigo: "96", descripcion: "96 - Autoconsumo: Potencia contratada mayor a 100kW" },
    { codigo: "97", descripcion: "97 - Autoconsumo: Potencia contratada menor a la instalada en generación" },
    { codigo: "98", descripcion: "98 - Autoconsumo: periodo mínimo de permanencia en modalidad de autoconsumo no respetado" },
    { codigo: "A1", descripcion: "A1 - Incidencia no subsanada" },
    { codigo: "A2", descripcion: "A2 - Contrato cortado por el distribuidor" },
    { codigo: "A3", descripcion: "A3 - Instalación peligrosa" },
    { codigo: "A4", descripcion: "A4 - Rechazo a solicitud de la comercializadora" },
    { codigo: "A5", descripcion: "A5 - Potencia superior/inferior al tipo de contrato" },
    { codigo: "A6", descripcion: "A6 - Potencia solicitada difiere de la autorizada" },
    { codigo: "A7", descripcion: "A7 - Fecha de autorización vencida" },
    { codigo: "A8", descripcion: "A8 - Precisa autorización ministerial" },
    { codigo: "A9", descripcion: "A9 - Potencia Solicitada mayor que la Potencia Máxima Autorizada en alta tensión" },
    { codigo: "B1", descripcion: "B1 - Falta documentación técnica de alta tensión" },
    { codigo: "B2", descripcion: "B2 - Rechazo por Fraude contrastado" },
    { codigo: "B3", descripcion: "B3 - Punto de suministro no localizado" },
    { codigo: "B4", descripcion: "B4 - Comercializador fuera de su ámbito geográfico" },
    { codigo: "B5", descripcion: "B5 - Existencia de Solicitud previa en curso B1 (motivo 01)" },
    { codigo: "B6", descripcion: "B6 - Existencia de Solicitud previa en curso B1 (motivo 02)" },
    { codigo: "B7", descripcion: "B7 - Existencia de Solicitud previa en curso B1 (motivo 03)" },
    { codigo: "B7", descripcion: "B7 - Existencia de Solicitud previa en curso B1 (motivo 03)" },
    { codigo: "B8", descripcion: "B8 - Existencia de Solicitud previa en curso B1 (motivo 04)" },
    { codigo: "B8", descripcion: "B8 - Existencia de Solicitud previa en curso B1 (motivo 04)" },
    { codigo: "B9", descripcion: "B9 - Existencia de solicitud de baja por impago en curso no anulable B1 (motivo, 01, 02 (si la COR ha rechazado el traspaso y ya se han iniciado trabajos para dar de baja) 04 o motivo 03 en el proceso de baja del contrato de acceso)." },
    { codigo: "C1", descripcion: "C1 - Concurrencia con cambio de comercializador/Traspaso a la COR/Cambio titular por traspaso. Se prioriza la activación del cambio sobre la baja" },
    { codigo: "C2", descripcion: "C2 - Imposible reenganchar por causas técnicas" },
    { codigo: "C3", descripcion: "C3 - Comercializador en proceso de inhabilitación" },
    { codigo: "C4", descripcion: "C4 - Desconexión no posible técnicamente en Corte por peligrosidad" },
    { codigo: "C4", descripcion: "C4 - Desconexión no posible técnicamente en Corte por peligrosidad" },
    { codigo: "C5", descripcion: "C5 - No es posible solicitar un cambio/modificación/alta/baja a fecha fija para una fecha > 30 días naturales" },
    { codigo: "C6", descripcion: "C6 - Oposición expresa del titular en campo. Se adjunta documentación." },
    { codigo: "C7", descripcion: "C7 - Impedimento del Titular. Iniciar si procede, el proceso de fraude" },
    { codigo: "C8", descripcion: "C8 - Rechazo de la suspensión del suministro por concurrencia con baja por impago" },
    { codigo: "C9", descripcion: "C9 - Expediente erróneo o no existe" },
    { codigo: "D1", descripcion: "D1 - Suministro acogido a bono social" },
    { codigo: "D2", descripcion: "D2 - No es posible la anulación ya que no existe solicitud previa" },
    { codigo: "D3", descripcion: "D3 - No cumple con la potencia normalizada para el PS ni el múltiplo de potencia establecido" },
    { codigo: "D4", descripcion: "D4 - El tipo de tensión solicitada es la que ya tiene el PS." },
    { codigo: "D5", descripcion: "D5 - Falta documentación según lo establecido en la Ley 12/2017 de las Islas Baleares." },
    { codigo: "D6", descripcion: "D6 - Identificador del titular del proceso subyacente no coincide con el titular que pretende desistir" },
    { codigo: "D7", descripcion: "D7 - Desistimiento sobre un proceso de contratación en curso" },
    { codigo: "D8", descripcion: "D8 - Desistimiento no posible técnicamente en campo" },
    { codigo: "D9", descripcion: "D9 - Desistimiento no posible por movimiento de contratación posterior" },
    { codigo: "E1", descripcion: "E1 - Código de solicitud de referencia no existe en la distribuidora" },
    { codigo: "E2", descripcion: "E2 - El desistimiento no aplica al proceso subyacente" },
    { codigo: "E3", descripcion: "E3 - Desistimiento solicitado por Persona Jurídica" },
    { codigo: "E4", descripcion: "E4 - Impago Previo" },
    { codigo: "E5", descripcion: "E5 - CUPS sujeto a LOPD" },
    { codigo: "E6", descripcion: "E6 - Modificación del tipo de autoconsumo no permitida. No han trascurrido cuatro meses desde la última modificación." },
    { codigo: "E7", descripcion: "E7 - Falta acuerdo de reparto o/y fichero de Coeficientes/Acuerdo de reparto o/y fichero de coeficientes incorrecto/Faltan coeficientes de reparto en acuerdo fichero" },
    { codigo: "E8", descripcion: "E8 - No recibida información técnica de la CCAA (para BT y <100kW)." },
    { codigo: "E9", descripcion: "E9 - En el periodo establecido, no se han recibido el resto de solicitudes de modificación del colectivo" },
    { codigo: "F1", descripcion: "F1 - Disconformidad del consumidor a la información sobre autoconsumo" },
    { codigo: "G1", descripcion: "G1 - Sólo se podrá modificar:  -el tipo de identificador y el identificador o,  -nombre y apellidos (razón social)." },
    { codigo: "G2", descripcion: "G2 - Revisión interior incorrecta, debe aportar documentación técnica posterior a la revisión" },
    { codigo: "G3", descripcion: "G3 - Código solicitud ATR/reclamación anterior inexistente" },
    { codigo: "G4", descripcion: "G4 - Suministro Mínimo Vital" },
    { codigo: "G5", descripcion: "G5 - Este tipo de modificación (“M”/”B”) solo aplica a solicitudes de modificación (formato M1) de suministros en bono social (suministrados por COR)" },
    { codigo: "G6", descripcion: "G6 - No es posible modificar el acuerdo de reparto/ fichero de coeficientes si no ha transcurrido un mínimo de 4 meses desde la última modificación" },
    { codigo: "G7", descripcion: "G7 - Si los SSAA no son despreciables y se da de alta un único contrato" },
    { codigo: "G8", descripcion: "G8 - La solicitud de modificación de autoconsumo coincide con la contratación en vigor." },
    { codigo: "G9", descripcion: "G9 - La solicitud de modificación no puede incorporar otras modificaciones técnicas" },
    { codigo: "H1", descripcion: "H1 - Tipo Autoconsumo no válido" },
    { codigo: "H2", descripcion: "H2 - Tipo Subsección no válido" },
    { codigo: "H3", descripcion: "H3 - Autoconsumo colectivo/individual" },
    { codigo: "H4", descripcion: "H4 - La instalación del cliente no puede tener vertidos a la red" },
    { codigo: "H5", descripcion: "H5 - No se puede solicitar una segunda modificación de potencia en un mismo ciclo de facturación" },
    { codigo: "H6", descripcion: "H6 - La reducción de potencia no cumple con los requisitos establecidos en el artículo 7 RDL 18/2022" },
    { codigo: "H7", descripcion: "H7 - Falta documentación de autoconsumo" },
    { codigo: "H8", descripcion: "H8 - Movimiento de cambio de acuerdo de reparto en vuelo" },
    { codigo: "H9", descripcion: "H9 - Solicitud ya realizada por otro" },
    { codigo: "I1", descripcion: "I1 - Identificador del titular que pretende reponer no coincide con el titular del contrato previo al proceso subyacente" },
    { codigo: "I2", descripcion: "I2 - Reposición solicitada en instalaciones superiores a 1 kV" },
    { codigo: "I3", descripcion: "I3 - La reposición no aplica al proceso subyacente" },
    { codigo: "I4", descripcion: "I4 - Reposición no posible técnicamente en campo" },
    { codigo: "I5", descripcion: "I5 - Reposición no posible por movimiento de contratación posterior" },
    { codigo: "I6", descripcion: "I6 - Reposición solicitada supera plazo máximo de 1 año" },
    { codigo: "I7", descripcion: "I7 - Concurrencia con proceso de reposición. Se prioriza la activación de la reposición" },
    { codigo: "I8", descripcion: "I8 - Existencia de una solicitud previa en curso" },
    { codigo: "J1", descripcion: "J1 - Vigencia del contrato que se pretende reponer está finalizado" },
    { codigo: "J2", descripcion: "J2 - Se dispone de aval documental acreditativo" },
    { codigo: "J3", descripcion: "J3 - Se rechaza reposición sin motivo específico" },
    { codigo: "J4", descripcion: "J4 - Modificación técnica solicitada coincide con la previa en distribuidor" },
    { codigo: "J5", descripcion: "J5 - Comercializador entrante rechaza la reposición" },
    { codigo: "J6", descripcion: "J6 - Reposición sobre un cambio de comercializador en curso" },
    { codigo: "99", descripcion: "99 - Otros" },
  ],
  "CONCEPTO CONTRATACION": [
    { codigo: "01", descripcion: "01 - No existe Punto de Suministro asociado al CUPS" },
    { codigo: "02", descripcion: "02 - Inexistencia de Contrato de ATR previo en vigor" },
    { codigo: "03", descripcion: "03 - NIF-CIF No coincide con el del Contrato en vigor" },
    { codigo: "03", descripcion: "03 - NIF-CIF No coincide con el del Contrato en vigor" },
    { codigo: "06", descripcion: "06 - Existencia de Solicitud ATR previa en curso" },
    { codigo: "07", descripcion: "07 - Tipo de Contrato sin informar o erróneo" },
    { codigo: "08", descripcion: "08 - Fecha de finalización del Contrato sin informar o no válida" },
    { codigo: "09", descripcion: "09 - Existencia de sentencia judicial relativa a deuda del cliente" },
    { codigo: "11", descripcion: "11 - Comercializadora incorrecta" },
    { codigo: "12", descripcion: "12 - Contrato cortado por impago" },
    { codigo: "12", descripcion: "12 - Contrato cortado por impago" },
    { codigo: "13", descripcion: "13 - Potencias No Normalizadas en Tarifas 2.XA y 2.XDHA" },
    { codigo: "14", descripcion: "14 - Potencia Solicitada mayor que la Potencia Máxima Autorizada en baja tensión" },
    { codigo: "15", descripcion: "15 - Secuencia de Potencias incorrectas, Pi>Pi+1" },
    { codigo: "17", descripcion: "17 - Tarifa no válida para la Tensión de Suministro" },
    { codigo: "18", descripcion: "18 - Equipo nuevo propiedad del Cliente no cumple los criterios de Contratación ATR" },
    { codigo: "20", descripcion: "20 - Instalación no disponible o ampliación suministro en trámite (Expediente Abierto + Código de Expediente + Motivo de Expediente)" },
    { codigo: "21", descripcion: "21 - Existencia de Contrato Previo en vigor" },
    { codigo: "22", descripcion: "22 - Potencia Solicitada mayor que la Potencia Máxima Reconocida de Extensión" },
    { codigo: "23", descripcion: "23 - CNAE No Informado o no válido" },
    { codigo: "25", descripcion: "25 - Ausencia del Titular con Cita" },
    { codigo: "26", descripcion: "26 - Acceso imposibilitado más de dos veces por causas ajenas a la Distribuidora" },
    { codigo: "27", descripcion: "27 - Caja ICP no válida o inexistente" },
    { codigo: "28", descripcion: "28 - Rechazo por Anormalidad" },
    { codigo: "29", descripcion: "29 - Falta Equipo Cliente" },
    { codigo: "31", descripcion: "31 - Impedimento del Titular" },
    { codigo: "32", descripcion: "32 - Suministro Esencial" },
    { codigo: "34", descripcion: "34 - Cliente no cortable por orden judicial o administrativa" },
    { codigo: "35", descripcion: "35 - Cliente ya cortado" },
    { codigo: "36", descripcion: "36 - NIF-CIF Erróneo" },
    { codigo: "37", descripcion: "37 - Existencia de Solicitud previa en curso A3" },
    { codigo: "38", descripcion: "38 - Existencia de Solicitud previa en curso C1" },
    { codigo: "39", descripcion: "39 - Existencia de Solicitud previa en curso C2" },
    { codigo: "40", descripcion: "40 - Existencia de Solicitud previa en curso M1" },
    { codigo: "41", descripcion: "41 - Existencia de Solicitud previa en curso B1 (motivo" },
    { codigo: "42", descripcion: "42 - No es posible anulación. OT ya en campo o acciones no anulables en una reclamación" },
    { codigo: "42", descripcion: "42 - No es posible anulación. OT ya en campo o acciones no anulables en una reclamación" },
    { codigo: "43", descripcion: "43 - No es posible anulación. Solicitud ya activada" },
    { codigo: "44", descripcion: "44 - Error en las horas de utilización (Eventuales)" },
    { codigo: "45", descripcion: "45 - Fecha de Finalización de Contrato sin informar (Eventuales, Temporada y Obras)" },
    { codigo: "46", descripcion: "46 - Fecha de la operación solicitada con carácter retroactivo" },
    { codigo: "47", descripcion: "47 - Potencias No Normalizadas en Suministro Trifásico" },
    { codigo: "48", descripcion: "48 - Potencias No Normalizadas en Suministro Monofásico" },
    { codigo: "49", descripcion: "49 - Necesario cambio de Tensión Monofásica a Trifásica" },
    { codigo: "50", descripcion: "50 - Transformadores de medida fuera de rango" },
    { codigo: "51", descripcion: "51 - Tarifa no válida para Contratos de Peaje" },
    { codigo: "52", descripcion: "52 - Tarifa no válida para Potencias Solicitadas" },
    { codigo: "53", descripcion: "53 - Necesidad de abrir Expediente de Acometida" },
    { codigo: "54", descripcion: "54 - No Existe Boletín Eventual" },
    { codigo: "55", descripcion: "55 - Nuevo Cliente coincide con el Actual" },
    { codigo: "56", descripcion: "56 - Falta de Datos en Campo 84 en Modificaciones" },
    { codigo: "57", descripcion: "57 - Falta documentación técnica de baja tensión" },
    { codigo: "58", descripcion: "58 - Falta teléfono de contacto" },
    { codigo: "58", descripcion: "58 - Falta teléfono de contacto" },
    { codigo: "59", descripcion: "59 - Armario / Módulo no válido o inexistente" },
    { codigo: "60", descripcion: "60 - Instalación incompleta o con elementos no válidos" },
    { codigo: "61", descripcion: "61 - CGP no válida o inexistente" },
    { codigo: "62", descripcion: "62 - Actuación Solicitada por Comercializador no acorde con requerimientos Cliente" },
    { codigo: "63", descripcion: "63 - Potencia Solicitada no puede ser inferior a Potencia de B.I.E. (Suministros en Modo 2 no interrumpibles)" },
    { codigo: "64", descripcion: "64 - Desconexión no posible técnicamente en Corte" },
    { codigo: "64", descripcion: "64 - Desconexión no posible técnicamente en Corte" },
    { codigo: "65", descripcion: "65 - Más de una modificación de potencia en un punto de suministro en menos de 12 meses para el mismo titular del punto de suministro" },
    { codigo: "66", descripcion: "66 - Suministro telegestionado." },
    { codigo: "67", descripcion: "67 - Suministro con maxímetro." },
    { codigo: "68", descripcion: "68 - No permitido a comercializadora de ML" },
    { codigo: "69", descripcion: "69 - El distribuidor no está de acuerdo" },
    { codigo: "70", descripcion: "70 - Comercializador inhabilitado" },
    { codigo: "71", descripcion: "71 - Existen varios cont. para el mismo suministro" },
    { codigo: "72", descripcion: "72 - Contrato en baja" },
    { codigo: "73", descripcion: "73 - Sum. Con potencia     > 15 kW." },
    { codigo: "73", descripcion: "73 - Sum. Con potencia     > 15 kW." },
    { codigo: "74", descripcion: "74 - Suministro con más de un contador" },
    { codigo: "75", descripcion: "75 - Discrepancia entre información de lecturas y número de integradores" },
    { codigo: "76", descripcion: "76 - Más dígitos que número de ruedas" },
    { codigo: "77", descripcion: "77 - Lectura menor a ultima real" },
    { codigo: "78", descripcion: "78 - Consumo excesivo" },
    { codigo: "79", descripcion: "79 - Periodo de lectura inferior" },
    { codigo: "80", descripcion: "80 - Suministro con maxímetro y/o reactiva" },
    { codigo: "83", descripcion: "83 - Pobreza Energética" },
    { codigo: "84", descripcion: "84 - Reclamación Duplicada" },
    { codigo: "85", descripcion: "85 - Falta campo obligatorio \"xxxx\"" },
    { codigo: "86", descripcion: "86 - Código de Expediente de Acometida Erróneo" },
    { codigo: "87", descripcion: "87 - Factura inexistente" },
    { codigo: "88", descripcion: "88 - Factura no telegestionada" },
    { codigo: "89", descripcion: "89 - No existe mejor curva disponible (no se genera curva)" },
    { codigo: "90", descripcion: "90 - Autoconsumo 1 o 2B: Titular del consumo no coincide con el de la instalación" },
    { codigo: "91", descripcion: "91 - Autoconsumo: Falta solicitud del contrato asociado" },
    { codigo: "91", descripcion: "91 - Autoconsumo: Falta solicitud del contrato asociado" },
    { codigo: "91", descripcion: "91 - Autoconsumo: Falta solicitud del contrato asociado" },
    { codigo: "92", descripcion: "92 - Autoconsumo: No coincide la categoría del autoconsumo de la solicitud con el registrado en Distribuidora." },
    { codigo: "93", descripcion: "93 - Autoconsumo:  Tipo de autoconsumo no válido." },
    { codigo: "94", descripcion: "94 - Autoconsumo: Imposible tramitar solicitud sobre ese suministro" },
    { codigo: "95", descripcion: "95 - Autoconsumo: Modalidad solicitada no coincide contrato técnico." },
    { codigo: "96", descripcion: "96 - Autoconsumo: Potencia contratada mayor a 100kW" },
    { codigo: "97", descripcion: "97 - Autoconsumo: Potencia contratada menor a la instalada en generación" },
    { codigo: "98", descripcion: "98 - Autoconsumo: periodo mínimo de permanencia en modalidad de autoconsumo no respetado" },
    { codigo: "A1", descripcion: "A1 - Incidencia no subsanada" },
    { codigo: "A2", descripcion: "A2 - Contrato cortado por el distribuidor" },
    { codigo: "A3", descripcion: "A3 - Instalación peligrosa" },
    { codigo: "A4", descripcion: "A4 - Rechazo a solicitud de la comercializadora" },
    { codigo: "A5", descripcion: "A5 - Potencia superior/inferior al tipo de contrato" },
    { codigo: "A6", descripcion: "A6 - Potencia solicitada difiere de la autorizada" },
    { codigo: "A7", descripcion: "A7 - Fecha de autorización vencida" },
    { codigo: "A8", descripcion: "A8 - Precisa autorización ministerial" },
    { codigo: "A9", descripcion: "A9 - Potencia Solicitada mayor que la Potencia Máxima Autorizada en alta tensión" },
    { codigo: "B1", descripcion: "B1 - Falta documentación técnica de alta tensión" },
    { codigo: "B2", descripcion: "B2 - Rechazo por Fraude contrastado" },
    { codigo: "B3", descripcion: "B3 - Punto de suministro no localizado" },
    { codigo: "B4", descripcion: "B4 - Comercializador fuera de su ámbito geográfico" },
    { codigo: "B5", descripcion: "B5 - Existencia de Solicitud previa en curso B1 (motivo 01)" },
    { codigo: "B6", descripcion: "B6 - Existencia de Solicitud previa en curso B1 (motivo 02)" },
    { codigo: "B7", descripcion: "B7 - Existencia de Solicitud previa en curso B1 (motivo 03)" },
    { codigo: "B7", descripcion: "B7 - Existencia de Solicitud previa en curso B1 (motivo 03)" },
    { codigo: "B8", descripcion: "B8 - Existencia de Solicitud previa en curso B1 (motivo 04)" },
    { codigo: "B8", descripcion: "B8 - Existencia de Solicitud previa en curso B1 (motivo 04)" },
    { codigo: "B9", descripcion: "B9 - Existencia de solicitud de baja por impago en curso no anulable B1 (motivo, 01, 02 (si la COR ha rechazado el traspaso y ya se han iniciado trabajos para dar de baja) 04 o motivo 03 en el proceso de baja del contrato de acceso)." },
    { codigo: "C1", descripcion: "C1 - Concurrencia con cambio de comercializador/Traspaso a la COR/Cambio titular por traspaso. Se prioriza la activación del cambio sobre la baja" },
    { codigo: "C2", descripcion: "C2 - Imposible reenganchar por causas técnicas" },
    { codigo: "C3", descripcion: "C3 - Comercializador en proceso de inhabilitación" },
    { codigo: "C4", descripcion: "C4 - Desconexión no posible técnicamente en Corte por peligrosidad" },
    { codigo: "C4", descripcion: "C4 - Desconexión no posible técnicamente en Corte por peligrosidad" },
    { codigo: "C5", descripcion: "C5 - No es posible solicitar un cambio/modificación/alta/baja a fecha fija para una fecha > 30 días naturales" },
    { codigo: "C6", descripcion: "C6 - Oposición expresa del titular en campo. Se adjunta documentación." },
    { codigo: "C7", descripcion: "C7 - Impedimento del Titular. Iniciar si procede, el proceso de fraude" },
    { codigo: "C8", descripcion: "C8 - Rechazo de la suspensión del suministro por concurrencia con baja por impago" },
    { codigo: "C9", descripcion: "C9 - Expediente erróneo o no existe" },
    { codigo: "D1", descripcion: "D1 - Suministro acogido a bono social" },
    { codigo: "D2", descripcion: "D2 - No es posible la anulación ya que no existe solicitud previa" },
    { codigo: "D3", descripcion: "D3 - No cumple con la potencia normalizada para el PS ni el múltiplo de potencia establecido" },
    { codigo: "D4", descripcion: "D4 - El tipo de tensión solicitada es la que ya tiene el PS." },
    { codigo: "D5", descripcion: "D5 - Falta documentación según lo establecido en la Ley 12/2017 de las Islas Baleares." },
    { codigo: "D6", descripcion: "D6 - Identificador del titular del proceso subyacente no coincide con el titular que pretende desistir" },
    { codigo: "D7", descripcion: "D7 - Desistimiento sobre un proceso de contratación en curso" },
    { codigo: "D8", descripcion: "D8 - Desistimiento no posible técnicamente en campo" },
    { codigo: "D9", descripcion: "D9 - Desistimiento no posible por movimiento de contratación posterior" },
    { codigo: "E1", descripcion: "E1 - Código de solicitud de referencia no existe en la distribuidora" },
    { codigo: "E2", descripcion: "E2 - El desistimiento no aplica al proceso subyacente" },
    { codigo: "E3", descripcion: "E3 - Desistimiento solicitado por Persona Jurídica" },
    { codigo: "E4", descripcion: "E4 - Impago Previo" },
    { codigo: "E5", descripcion: "E5 - CUPS sujeto a LOPD" },
    { codigo: "E6", descripcion: "E6 - Modificación del tipo de autoconsumo no permitida. No han trascurrido cuatro meses desde la última modificación." },
    { codigo: "E7", descripcion: "E7 - Falta acuerdo de reparto o/y fichero de Coeficientes/Acuerdo de reparto o/y fichero de coeficientes incorrecto/Faltan coeficientes de reparto en acuerdo fichero" },
    { codigo: "E8", descripcion: "E8 - No recibida información técnica de la CCAA (para BT y <100kW)." },
    { codigo: "E9", descripcion: "E9 - En el periodo establecido, no se han recibido el resto de solicitudes de modificación del colectivo" },
    { codigo: "F1", descripcion: "F1 - Disconformidad del consumidor a la información sobre autoconsumo" },
    { codigo: "G1", descripcion: "G1 - Sólo se podrá modificar:  -el tipo de identificador y el identificador o,  -nombre y apellidos (razón social)." },
    { codigo: "G2", descripcion: "G2 - Revisión interior incorrecta, debe aportar documentación técnica posterior a la revisión" },
    { codigo: "G3", descripcion: "G3 - Código solicitud ATR/reclamación anterior inexistente" },
    { codigo: "G4", descripcion: "G4 - Suministro Mínimo Vital" },
    { codigo: "G5", descripcion: "G5 - Este tipo de modificación (“M”/”B”) solo aplica a solicitudes de modificación (formato M1) de suministros en bono social (suministrados por COR)" },
    { codigo: "G6", descripcion: "G6 - No es posible modificar el acuerdo de reparto/ fichero de coeficientes si no ha transcurrido un mínimo de 4 meses desde la última modificación" },
    { codigo: "G7", descripcion: "G7 - Si los SSAA no son despreciables y se da de alta un único contrato" },
    { codigo: "G8", descripcion: "G8 - La solicitud de modificación de autoconsumo coincide con la contratación en vigor." },
    { codigo: "G9", descripcion: "G9 - La solicitud de modificación no puede incorporar otras modificaciones técnicas" },
    { codigo: "H1", descripcion: "H1 - Tipo Autoconsumo no válido" },
    { codigo: "H2", descripcion: "H2 - Tipo Subsección no válido" },
    { codigo: "H3", descripcion: "H3 - Autoconsumo colectivo/individual" },
    { codigo: "H4", descripcion: "H4 - La instalación del cliente no puede tener vertidos a la red" },
    { codigo: "H5", descripcion: "H5 - No se puede solicitar una segunda modificación de potencia en un mismo ciclo de facturación" },
    { codigo: "H6", descripcion: "H6 - La reducción de potencia no cumple con los requisitos establecidos en el artículo 7 RDL 18/2022" },
    { codigo: "H7", descripcion: "H7 - Falta documentación de autoconsumo" },
    { codigo: "H8", descripcion: "H8 - Movimiento de cambio de acuerdo de reparto en vuelo" },
    { codigo: "H9", descripcion: "H9 - Solicitud ya realizada por otro" },
    { codigo: "I1", descripcion: "I1 - Identificador del titular que pretende reponer no coincide con el titular del contrato previo al proceso subyacente" },
    { codigo: "I2", descripcion: "I2 - Reposición solicitada en instalaciones superiores a 1 kV" },
    { codigo: "I3", descripcion: "I3 - La reposición no aplica al proceso subyacente" },
    { codigo: "I4", descripcion: "I4 - Reposición no posible técnicamente en campo" },
    { codigo: "I5", descripcion: "I5 - Reposición no posible por movimiento de contratación posterior" },
    { codigo: "I6", descripcion: "I6 - Reposición solicitada supera plazo máximo de 1 año" },
    { codigo: "I7", descripcion: "I7 - Concurrencia con proceso de reposición. Se prioriza la activación de la reposición" },
    { codigo: "I8", descripcion: "I8 - Existencia de una solicitud previa en curso" },
    { codigo: "J1", descripcion: "J1 - Vigencia del contrato que se pretende reponer está finalizado" },
    { codigo: "J2", descripcion: "J2 - Se dispone de aval documental acreditativo" },
    { codigo: "J3", descripcion: "J3 - Se rechaza reposición sin motivo específico" },
    { codigo: "J4", descripcion: "J4 - Modificación técnica solicitada coincide con la previa en distribuidor" },
    { codigo: "J5", descripcion: "J5 - Comercializador entrante rechaza la reposición" },
    { codigo: "J6", descripcion: "J6 - Reposición sobre un cambio de comercializador en curso" },
    { codigo: "99", descripcion: "99 - Otros" },
  ],
  "MOTIVO CONSULTA": [
    { codigo: "01", descripcion: "01 - No existe Punto de Suministro asociado al CUPS" },
    { codigo: "02", descripcion: "02 - Inexistencia de Contrato de ATR previo en vigor" },
    { codigo: "03", descripcion: "03 - NIF-CIF No coincide con el del Contrato en vigor" },
    { codigo: "03", descripcion: "03 - NIF-CIF No coincide con el del Contrato en vigor" },
    { codigo: "06", descripcion: "06 - Existencia de Solicitud ATR previa en curso" },
    { codigo: "07", descripcion: "07 - Tipo de Contrato sin informar o erróneo" },
    { codigo: "08", descripcion: "08 - Fecha de finalización del Contrato sin informar o no válida" },
    { codigo: "09", descripcion: "09 - Existencia de sentencia judicial relativa a deuda del cliente" },
    { codigo: "11", descripcion: "11 - Comercializadora incorrecta" },
    { codigo: "12", descripcion: "12 - Contrato cortado por impago" },
    { codigo: "12", descripcion: "12 - Contrato cortado por impago" },
    { codigo: "13", descripcion: "13 - Potencias No Normalizadas en Tarifas 2.XA y 2.XDHA" },
    { codigo: "14", descripcion: "14 - Potencia Solicitada mayor que la Potencia Máxima Autorizada en baja tensión" },
    { codigo: "15", descripcion: "15 - Secuencia de Potencias incorrectas, Pi>Pi+1" },
    { codigo: "17", descripcion: "17 - Tarifa no válida para la Tensión de Suministro" },
    { codigo: "18", descripcion: "18 - Equipo nuevo propiedad del Cliente no cumple los criterios de Contratación ATR" },
    { codigo: "20", descripcion: "20 - Instalación no disponible o ampliación suministro en trámite (Expediente Abierto + Código de Expediente + Motivo de Expediente)" },
    { codigo: "21", descripcion: "21 - Existencia de Contrato Previo en vigor" },
    { codigo: "22", descripcion: "22 - Potencia Solicitada mayor que la Potencia Máxima Reconocida de Extensión" },
    { codigo: "23", descripcion: "23 - CNAE No Informado o no válido" },
    { codigo: "25", descripcion: "25 - Ausencia del Titular con Cita" },
    { codigo: "26", descripcion: "26 - Acceso imposibilitado más de dos veces por causas ajenas a la Distribuidora" },
    { codigo: "27", descripcion: "27 - Caja ICP no válida o inexistente" },
    { codigo: "28", descripcion: "28 - Rechazo por Anormalidad" },
    { codigo: "29", descripcion: "29 - Falta Equipo Cliente" },
    { codigo: "31", descripcion: "31 - Impedimento del Titular" },
    { codigo: "32", descripcion: "32 - Suministro Esencial" },
    { codigo: "34", descripcion: "34 - Cliente no cortable por orden judicial o administrativa" },
    { codigo: "35", descripcion: "35 - Cliente ya cortado" },
    { codigo: "36", descripcion: "36 - NIF-CIF Erróneo" },
    { codigo: "37", descripcion: "37 - Existencia de Solicitud previa en curso A3" },
    { codigo: "38", descripcion: "38 - Existencia de Solicitud previa en curso C1" },
    { codigo: "39", descripcion: "39 - Existencia de Solicitud previa en curso C2" },
    { codigo: "40", descripcion: "40 - Existencia de Solicitud previa en curso M1" },
    { codigo: "41", descripcion: "41 - Existencia de Solicitud previa en curso B1 (motivo" },
    { codigo: "42", descripcion: "42 - No es posible anulación. OT ya en campo o acciones no anulables en una reclamación" },
    { codigo: "42", descripcion: "42 - No es posible anulación. OT ya en campo o acciones no anulables en una reclamación" },
    { codigo: "43", descripcion: "43 - No es posible anulación. Solicitud ya activada" },
    { codigo: "44", descripcion: "44 - Error en las horas de utilización (Eventuales)" },
    { codigo: "45", descripcion: "45 - Fecha de Finalización de Contrato sin informar (Eventuales, Temporada y Obras)" },
    { codigo: "46", descripcion: "46 - Fecha de la operación solicitada con carácter retroactivo" },
    { codigo: "47", descripcion: "47 - Potencias No Normalizadas en Suministro Trifásico" },
    { codigo: "48", descripcion: "48 - Potencias No Normalizadas en Suministro Monofásico" },
    { codigo: "49", descripcion: "49 - Necesario cambio de Tensión Monofásica a Trifásica" },
    { codigo: "50", descripcion: "50 - Transformadores de medida fuera de rango" },
    { codigo: "51", descripcion: "51 - Tarifa no válida para Contratos de Peaje" },
    { codigo: "52", descripcion: "52 - Tarifa no válida para Potencias Solicitadas" },
    { codigo: "53", descripcion: "53 - Necesidad de abrir Expediente de Acometida" },
    { codigo: "54", descripcion: "54 - No Existe Boletín Eventual" },
    { codigo: "55", descripcion: "55 - Nuevo Cliente coincide con el Actual" },
    { codigo: "56", descripcion: "56 - Falta de Datos en Campo 84 en Modificaciones" },
    { codigo: "57", descripcion: "57 - Falta documentación técnica de baja tensión" },
    { codigo: "58", descripcion: "58 - Falta teléfono de contacto" },
    { codigo: "58", descripcion: "58 - Falta teléfono de contacto" },
    { codigo: "59", descripcion: "59 - Armario / Módulo no válido o inexistente" },
    { codigo: "60", descripcion: "60 - Instalación incompleta o con elementos no válidos" },
    { codigo: "61", descripcion: "61 - CGP no válida o inexistente" },
    { codigo: "62", descripcion: "62 - Actuación Solicitada por Comercializador no acorde con requerimientos Cliente" },
    { codigo: "63", descripcion: "63 - Potencia Solicitada no puede ser inferior a Potencia de B.I.E. (Suministros en Modo 2 no interrumpibles)" },
    { codigo: "64", descripcion: "64 - Desconexión no posible técnicamente en Corte" },
    { codigo: "64", descripcion: "64 - Desconexión no posible técnicamente en Corte" },
    { codigo: "65", descripcion: "65 - Más de una modificación de potencia en un punto de suministro en menos de 12 meses para el mismo titular del punto de suministro" },
    { codigo: "66", descripcion: "66 - Suministro telegestionado." },
    { codigo: "67", descripcion: "67 - Suministro con maxímetro." },
    { codigo: "68", descripcion: "68 - No permitido a comercializadora de ML" },
    { codigo: "69", descripcion: "69 - El distribuidor no está de acuerdo" },
    { codigo: "70", descripcion: "70 - Comercializador inhabilitado" },
    { codigo: "71", descripcion: "71 - Existen varios cont. para el mismo suministro" },
    { codigo: "72", descripcion: "72 - Contrato en baja" },
    { codigo: "73", descripcion: "73 - Sum. Con potencia     > 15 kW." },
    { codigo: "73", descripcion: "73 - Sum. Con potencia     > 15 kW." },
    { codigo: "74", descripcion: "74 - Suministro con más de un contador" },
    { codigo: "75", descripcion: "75 - Discrepancia entre información de lecturas y número de integradores" },
    { codigo: "76", descripcion: "76 - Más dígitos que número de ruedas" },
    { codigo: "77", descripcion: "77 - Lectura menor a ultima real" },
    { codigo: "78", descripcion: "78 - Consumo excesivo" },
    { codigo: "79", descripcion: "79 - Periodo de lectura inferior" },
    { codigo: "80", descripcion: "80 - Suministro con maxímetro y/o reactiva" },
    { codigo: "83", descripcion: "83 - Pobreza Energética" },
    { codigo: "84", descripcion: "84 - Reclamación Duplicada" },
    { codigo: "85", descripcion: "85 - Falta campo obligatorio \"xxxx\"" },
    { codigo: "86", descripcion: "86 - Código de Expediente de Acometida Erróneo" },
    { codigo: "87", descripcion: "87 - Factura inexistente" },
    { codigo: "88", descripcion: "88 - Factura no telegestionada" },
    { codigo: "89", descripcion: "89 - No existe mejor curva disponible (no se genera curva)" },
    { codigo: "90", descripcion: "90 - Autoconsumo 1 o 2B: Titular del consumo no coincide con el de la instalación" },
    { codigo: "91", descripcion: "91 - Autoconsumo: Falta solicitud del contrato asociado" },
    { codigo: "91", descripcion: "91 - Autoconsumo: Falta solicitud del contrato asociado" },
    { codigo: "91", descripcion: "91 - Autoconsumo: Falta solicitud del contrato asociado" },
    { codigo: "92", descripcion: "92 - Autoconsumo: No coincide la categoría del autoconsumo de la solicitud con el registrado en Distribuidora." },
    { codigo: "93", descripcion: "93 - Autoconsumo:  Tipo de autoconsumo no válido." },
    { codigo: "94", descripcion: "94 - Autoconsumo: Imposible tramitar solicitud sobre ese suministro" },
    { codigo: "95", descripcion: "95 - Autoconsumo: Modalidad solicitada no coincide contrato técnico." },
    { codigo: "96", descripcion: "96 - Autoconsumo: Potencia contratada mayor a 100kW" },
    { codigo: "97", descripcion: "97 - Autoconsumo: Potencia contratada menor a la instalada en generación" },
    { codigo: "98", descripcion: "98 - Autoconsumo: periodo mínimo de permanencia en modalidad de autoconsumo no respetado" },
    { codigo: "A1", descripcion: "A1 - Incidencia no subsanada" },
    { codigo: "A2", descripcion: "A2 - Contrato cortado por el distribuidor" },
    { codigo: "A3", descripcion: "A3 - Instalación peligrosa" },
    { codigo: "A4", descripcion: "A4 - Rechazo a solicitud de la comercializadora" },
    { codigo: "A5", descripcion: "A5 - Potencia superior/inferior al tipo de contrato" },
    { codigo: "A6", descripcion: "A6 - Potencia solicitada difiere de la autorizada" },
    { codigo: "A7", descripcion: "A7 - Fecha de autorización vencida" },
    { codigo: "A8", descripcion: "A8 - Precisa autorización ministerial" },
    { codigo: "A9", descripcion: "A9 - Potencia Solicitada mayor que la Potencia Máxima Autorizada en alta tensión" },
    { codigo: "B1", descripcion: "B1 - Falta documentación técnica de alta tensión" },
    { codigo: "B2", descripcion: "B2 - Rechazo por Fraude contrastado" },
    { codigo: "B3", descripcion: "B3 - Punto de suministro no localizado" },
    { codigo: "B4", descripcion: "B4 - Comercializador fuera de su ámbito geográfico" },
    { codigo: "B5", descripcion: "B5 - Existencia de Solicitud previa en curso B1 (motivo 01)" },
    { codigo: "B6", descripcion: "B6 - Existencia de Solicitud previa en curso B1 (motivo 02)" },
    { codigo: "B7", descripcion: "B7 - Existencia de Solicitud previa en curso B1 (motivo 03)" },
    { codigo: "B7", descripcion: "B7 - Existencia de Solicitud previa en curso B1 (motivo 03)" },
    { codigo: "B8", descripcion: "B8 - Existencia de Solicitud previa en curso B1 (motivo 04)" },
    { codigo: "B8", descripcion: "B8 - Existencia de Solicitud previa en curso B1 (motivo 04)" },
    { codigo: "B9", descripcion: "B9 - Existencia de solicitud de baja por impago en curso no anulable B1 (motivo, 01, 02 (si la COR ha rechazado el traspaso y ya se han iniciado trabajos para dar de baja) 04 o motivo 03 en el proceso de baja del contrato de acceso)." },
    { codigo: "C1", descripcion: "C1 - Concurrencia con cambio de comercializador/Traspaso a la COR/Cambio titular por traspaso. Se prioriza la activación del cambio sobre la baja" },
    { codigo: "C2", descripcion: "C2 - Imposible reenganchar por causas técnicas" },
    { codigo: "C3", descripcion: "C3 - Comercializador en proceso de inhabilitación" },
    { codigo: "C4", descripcion: "C4 - Desconexión no posible técnicamente en Corte por peligrosidad" },
    { codigo: "C4", descripcion: "C4 - Desconexión no posible técnicamente en Corte por peligrosidad" },
    { codigo: "C5", descripcion: "C5 - No es posible solicitar un cambio/modificación/alta/baja a fecha fija para una fecha > 30 días naturales" },
    { codigo: "C6", descripcion: "C6 - Oposición expresa del titular en campo. Se adjunta documentación." },
    { codigo: "C7", descripcion: "C7 - Impedimento del Titular. Iniciar si procede, el proceso de fraude" },
    { codigo: "C8", descripcion: "C8 - Rechazo de la suspensión del suministro por concurrencia con baja por impago" },
    { codigo: "C9", descripcion: "C9 - Expediente erróneo o no existe" },
    { codigo: "D1", descripcion: "D1 - Suministro acogido a bono social" },
    { codigo: "D2", descripcion: "D2 - No es posible la anulación ya que no existe solicitud previa" },
    { codigo: "D3", descripcion: "D3 - No cumple con la potencia normalizada para el PS ni el múltiplo de potencia establecido" },
    { codigo: "D4", descripcion: "D4 - El tipo de tensión solicitada es la que ya tiene el PS." },
    { codigo: "D5", descripcion: "D5 - Falta documentación según lo establecido en la Ley 12/2017 de las Islas Baleares." },
    { codigo: "D6", descripcion: "D6 - Identificador del titular del proceso subyacente no coincide con el titular que pretende desistir" },
    { codigo: "D7", descripcion: "D7 - Desistimiento sobre un proceso de contratación en curso" },
    { codigo: "D8", descripcion: "D8 - Desistimiento no posible técnicamente en campo" },
    { codigo: "D9", descripcion: "D9 - Desistimiento no posible por movimiento de contratación posterior" },
    { codigo: "E1", descripcion: "E1 - Código de solicitud de referencia no existe en la distribuidora" },
    { codigo: "E2", descripcion: "E2 - El desistimiento no aplica al proceso subyacente" },
    { codigo: "E3", descripcion: "E3 - Desistimiento solicitado por Persona Jurídica" },
    { codigo: "E4", descripcion: "E4 - Impago Previo" },
    { codigo: "E5", descripcion: "E5 - CUPS sujeto a LOPD" },
    { codigo: "E6", descripcion: "E6 - Modificación del tipo de autoconsumo no permitida. No han trascurrido cuatro meses desde la última modificación." },
    { codigo: "E7", descripcion: "E7 - Falta acuerdo de reparto o/y fichero de Coeficientes/Acuerdo de reparto o/y fichero de coeficientes incorrecto/Faltan coeficientes de reparto en acuerdo fichero" },
    { codigo: "E8", descripcion: "E8 - No recibida información técnica de la CCAA (para BT y <100kW)." },
    { codigo: "E9", descripcion: "E9 - En el periodo establecido, no se han recibido el resto de solicitudes de modificación del colectivo" },
    { codigo: "F1", descripcion: "F1 - Disconformidad del consumidor a la información sobre autoconsumo" },
    { codigo: "G1", descripcion: "G1 - Sólo se podrá modificar:  -el tipo de identificador y el identificador o,  -nombre y apellidos (razón social)." },
    { codigo: "G2", descripcion: "G2 - Revisión interior incorrecta, debe aportar documentación técnica posterior a la revisión" },
    { codigo: "G3", descripcion: "G3 - Código solicitud ATR/reclamación anterior inexistente" },
    { codigo: "G4", descripcion: "G4 - Suministro Mínimo Vital" },
    { codigo: "G5", descripcion: "G5 - Este tipo de modificación (“M”/”B”) solo aplica a solicitudes de modificación (formato M1) de suministros en bono social (suministrados por COR)" },
    { codigo: "G6", descripcion: "G6 - No es posible modificar el acuerdo de reparto/ fichero de coeficientes si no ha transcurrido un mínimo de 4 meses desde la última modificación" },
    { codigo: "G7", descripcion: "G7 - Si los SSAA no son despreciables y se da de alta un único contrato" },
    { codigo: "G8", descripcion: "G8 - La solicitud de modificación de autoconsumo coincide con la contratación en vigor." },
    { codigo: "G9", descripcion: "G9 - La solicitud de modificación no puede incorporar otras modificaciones técnicas" },
    { codigo: "H1", descripcion: "H1 - Tipo Autoconsumo no válido" },
    { codigo: "H2", descripcion: "H2 - Tipo Subsección no válido" },
    { codigo: "H3", descripcion: "H3 - Autoconsumo colectivo/individual" },
    { codigo: "H4", descripcion: "H4 - La instalación del cliente no puede tener vertidos a la red" },
    { codigo: "H5", descripcion: "H5 - No se puede solicitar una segunda modificación de potencia en un mismo ciclo de facturación" },
    { codigo: "H6", descripcion: "H6 - La reducción de potencia no cumple con los requisitos establecidos en el artículo 7 RDL 18/2022" },
    { codigo: "H7", descripcion: "H7 - Falta documentación de autoconsumo" },
    { codigo: "H8", descripcion: "H8 - Movimiento de cambio de acuerdo de reparto en vuelo" },
    { codigo: "H9", descripcion: "H9 - Solicitud ya realizada por otro" },
    { codigo: "I1", descripcion: "I1 - Identificador del titular que pretende reponer no coincide con el titular del contrato previo al proceso subyacente" },
    { codigo: "I2", descripcion: "I2 - Reposición solicitada en instalaciones superiores a 1 kV" },
    { codigo: "I3", descripcion: "I3 - La reposición no aplica al proceso subyacente" },
    { codigo: "I4", descripcion: "I4 - Reposición no posible técnicamente en campo" },
    { codigo: "I5", descripcion: "I5 - Reposición no posible por movimiento de contratación posterior" },
    { codigo: "I6", descripcion: "I6 - Reposición solicitada supera plazo máximo de 1 año" },
    { codigo: "I7", descripcion: "I7 - Concurrencia con proceso de reposición. Se prioriza la activación de la reposición" },
    { codigo: "I8", descripcion: "I8 - Existencia de una solicitud previa en curso" },
    { codigo: "J1", descripcion: "J1 - Vigencia del contrato que se pretende reponer está finalizado" },
    { codigo: "J2", descripcion: "J2 - Se dispone de aval documental acreditativo" },
    { codigo: "J3", descripcion: "J3 - Se rechaza reposición sin motivo específico" },
    { codigo: "J4", descripcion: "J4 - Modificación técnica solicitada coincide con la previa en distribuidor" },
    { codigo: "J5", descripcion: "J5 - Comercializador entrante rechaza la reposición" },
    { codigo: "J6", descripcion: "J6 - Reposición sobre un cambio de comercializador en curso" },
    { codigo: "99", descripcion: "99 - Otros" },
  ],
  "CODIGO INCIDENCIA": [
    { codigo: "01", descripcion: "01 - Comprobación" },
    { codigo: "02", descripcion: "02 - Verificación con patrón" },
    { codigo: "03", descripcion: "03 - Contador robado/ Sin contador" },
    { codigo: "04", descripcion: "04 - Contador averiado: parado, pantalla apagada/falla, sigue contando sin nada conectado en domicilio, quemado, error conexionado, suministro sin tensión." },
    { codigo: "05", descripcion: "05 - Incidencias ICP" },
    { codigo: "06", descripcion: "06 - Contador desprogramado: DH o reloj desprogramado (sólo marca en punta o en valle o las muestra cambiadas, dígitos contador no se corresponde con factura." },
    { codigo: "07", descripcion: "07 - Incidencia en el equipo de telemedida" },
  ],
  "TIPO CONCEPTO FACTURADO": [],
  "TIPO DISCONFORME AUTOCONSUMO": [],
};